-- =============================================
-- Run this in your Supabase SQL Editor
-- =============================================

-- 1. Daily reports (existing, keep as-is)
CREATE TABLE IF NOT EXISTS daily_reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL,
  date DATE NOT NULL,
  total_sessions INTEGER NOT NULL,
  id_retake INTEGER NOT NULL,
  tech_issue INTEGER NOT NULL,
  system_issue INTEGER NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Teams
CREATE TABLE IF NOT EXISTS teams (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 3. Users (agents + TL)
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  team_id BIGINT REFERENCES teams(id) ON DELETE SET NULL,
  password TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'agent',
  created_at TIMESTAMPTZ DEFAULT now()
);

-- =============================================
-- Seed example data (edit as needed)
-- =============================================
INSERT INTO teams (name) VALUES ('Team Alpha'), ('Team Beta')
ON CONFLICT (name) DO NOTHING;

-- To add users, insert rows like:
-- INSERT INTO users (name, team_id, password, role)
-- VALUES ('John Doe', 1, 'pass123', 'agent');
-- TL password is set via ADMIN_PASSWORD on your backend host

-- Access codes (linked to each daily report)
CREATE TABLE IF NOT EXISTS access_codes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  report_id BIGINT REFERENCES daily_reports(id) ON DELETE CASCADE,
  code TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_access_codes_report_id ON access_codes(report_id);
