-- =============================================
-- Fresh schema for Ops System
-- Run this in Supabase SQL Editor for new installs.
-- =============================================

CREATE TABLE IF NOT EXISTS teams (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  team_id BIGINT REFERENCES teams(id) ON DELETE SET NULL,
  password TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'agent',
  email TEXT,
  shift_start TIME NOT NULL DEFAULT '09:00',
  shift_end TIME NOT NULL DEFAULT '18:00',
  week_offs TEXT[] NOT NULL DEFAULT ARRAY['saturday', 'sunday'],
  timezone TEXT NOT NULL DEFAULT 'Asia/Kolkata',
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS daily_reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  date DATE NOT NULL,
  total_sessions INTEGER NOT NULL DEFAULT 0,
  id_retake INTEGER NOT NULL DEFAULT 0,
  tech_issue INTEGER NOT NULL DEFAULT 0,
  system_issue INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT now() NOT NULL,
  CONSTRAINT daily_reports_user_date_unique UNIQUE (user_id, date)
);

CREATE TABLE IF NOT EXISTS access_codes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  report_id BIGINT NOT NULL REFERENCES daily_reports(id) ON DELETE CASCADE,
  code TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
  CONSTRAINT access_codes_report_code_unique UNIQUE (report_id, code)
);

CREATE INDEX IF NOT EXISTS idx_access_codes_report_id ON access_codes(report_id);

CREATE TABLE IF NOT EXISTS leave_dates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  date DATE NOT NULL,
  reason TEXT,
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
  CONSTRAINT leave_dates_user_date_unique UNIQUE (user_id, date)
);

CREATE TABLE IF NOT EXISTS report_reminders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  reminder_date DATE NOT NULL,
  kind TEXT NOT NULL DEFAULT 'missing_report',
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
  CONSTRAINT report_reminders_user_date_kind_unique UNIQUE (user_id, reminder_date, kind)
);

INSERT INTO teams (name) VALUES ('Team Alpha'), ('Team Beta')
ON CONFLICT (name) DO NOTHING;

-- Example user insert:
-- INSERT INTO users (name, team_id, password, role, email)
-- VALUES ('John Doe', 1, 'pass123', 'agent', 'john@example.com');
