-- Run this in your Supabase SQL Editor to create the necessary table

CREATE TABLE IF NOT EXISTS daily_reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL,
  date DATE NOT NULL,
  total_sessions INTEGER NOT NULL,
  id_retake INTEGER NOT NULL,
  tech_issue INTEGER NOT NULL,
  system_issue INTEGER NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Optional: Add Row Level Security (RLS) policies if you plan to access this from the frontend directly
-- For now, since the backend handles the inserts and reads, we can leave RLS disabled or enable it and allow service role access.
-- ALTER TABLE daily_reports ENABLE ROW LEVEL SECURITY;
