-- One-time migration for existing Ops System databases.
-- Run this after backing up the database.

ALTER TABLE users
  ADD COLUMN IF NOT EXISTS email TEXT,
  ADD COLUMN IF NOT EXISTS shift_start TIME NOT NULL DEFAULT '09:00',
  ADD COLUMN IF NOT EXISTS shift_end TIME NOT NULL DEFAULT '18:00',
  ADD COLUMN IF NOT EXISTS week_offs TEXT[] NOT NULL DEFAULT ARRAY['saturday', 'sunday'],
  ADD COLUMN IF NOT EXISTS timezone TEXT NOT NULL DEFAULT 'Asia/Kolkata';

ALTER TABLE daily_reports
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT now();

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM daily_reports dr
    LEFT JOIN users u ON u.name = dr.user_id
    WHERE u.id IS NULL
  ) THEN
    RAISE EXCEPTION 'Migration aborted: some daily_reports.user_id values do not match users.name';
  END IF;
END $$;

ALTER TABLE daily_reports ADD COLUMN user_id_new BIGINT;

UPDATE daily_reports dr
SET user_id_new = u.id
FROM users u
WHERE u.name = dr.user_id;

CREATE TEMP TABLE daily_reports_agg AS
SELECT
  MIN(id) AS keep_id,
  user_id_new AS user_id,
  date,
  SUM(total_sessions) AS total_sessions,
  SUM(id_retake) AS id_retake,
  SUM(tech_issue) AS tech_issue,
  SUM(system_issue) AS system_issue,
  MAX(updated_at) AS updated_at
FROM daily_reports
GROUP BY user_id_new, date;

UPDATE daily_reports dr
SET
  total_sessions = agg.total_sessions,
  id_retake = agg.id_retake,
  tech_issue = agg.tech_issue,
  system_issue = agg.system_issue,
  updated_at = agg.updated_at
FROM daily_reports_agg agg
WHERE dr.id = agg.keep_id;

UPDATE access_codes ac
SET report_id = agg.keep_id
FROM daily_reports dr
JOIN daily_reports_agg agg
  ON agg.user_id = dr.user_id_new
 AND agg.date = dr.date
WHERE ac.report_id = dr.id
  AND dr.id <> agg.keep_id;

DELETE FROM daily_reports dr
USING daily_reports_agg agg
WHERE dr.user_id_new = agg.user_id
  AND dr.date = agg.date
  AND dr.id <> agg.keep_id;

ALTER TABLE daily_reports ALTER COLUMN user_id_new SET NOT NULL;
ALTER TABLE daily_reports DROP COLUMN user_id;
ALTER TABLE daily_reports RENAME COLUMN user_id_new TO user_id;
ALTER TABLE daily_reports
  ADD CONSTRAINT daily_reports_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE daily_reports
  ADD CONSTRAINT daily_reports_user_date_unique UNIQUE (user_id, date);

DELETE FROM access_codes a
USING access_codes b
WHERE a.id > b.id
  AND a.report_id = b.report_id
  AND a.code = b.code;

ALTER TABLE access_codes
  ADD CONSTRAINT access_codes_report_code_unique UNIQUE (report_id, code);

CREATE TABLE IF NOT EXISTS leave_dates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  date DATE NOT NULL,
  reason TEXT,
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
  CONSTRAINT leave_dates_user_date_unique UNIQUE (user_id, date)
);

CREATE TABLE IF NOT EXISTS report_reminders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  reminder_date DATE NOT NULL,
  kind TEXT NOT NULL DEFAULT 'missing_report',
  created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
  CONSTRAINT report_reminders_user_date_kind_unique UNIQUE (user_id, reminder_date, kind)
);
